<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="0" failed="0" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-21T12:02:52Z" name="Default suite" finished-at="2022-06-21T12:02:52Z" duration-ms="23">
    <groups>
    </groups>
    <test started-at="2022-06-21T12:02:52Z" name="Default test" finished-at="2022-06-21T12:02:52Z" duration-ms="23">
      <class name="com.Axisring.pom.testcases.Login">
        <test-method is-config="true" signature="startTest()[pri:0, instance:com.Axisring.pom.testcases.Login@4c4d27c8]" started-at="2022-06-21T17:32:52Z" name="startTest" finished-at="2022-06-21T17:32:52Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "com.Axisring.pom.testcases.base.BaseTest.startExtent" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "com.Axisring.pom.testcases.base.BaseTest.startExtent" is null
	at com.Axisring.pom.testcases.base.BaseTest.reportFailure(BaseTest.java:176)
	at com.Axisring.pom.testcases.base.BaseTest.init(BaseTest.java:96)
	at com.Axisring.pom.testcases.base.BaseTest.startTest(BaseTest.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:298)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="Loging()[pri:0, instance:com.Axisring.pom.testcases.Login@4c4d27c8]" started-at="2022-06-21T17:32:52Z" name="Loging" finished-at="2022-06-21T17:32:52Z" duration-ms="2" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loging -->
        <test-method signature="Loging_module()[pri:0, instance:com.Axisring.pom.testcases.Login@4c4d27c8]" started-at="2022-06-21T17:32:52Z" name="Loging_module" finished-at="2022-06-21T17:32:52Z" duration-ms="2" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Loging_module -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.Axisring.pom.testcases.Login@4c4d27c8]" started-at="2022-06-21T17:32:52Z" name="quit" finished-at="2022-06-21T17:32:52Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.Axisring.pom.testcases.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
